name: Bug report
description: Use this template to report bugs
labels: ["type:bug"]
body:
  - type: markdown
    attributes:
      value: >
        **Note:** If this is a support question (e.g. _How do I do XYZ?_), please post on the [Google Developers Community](https://discord.gg/google-dev-community) Discord server's #palm-api channel instead. This is a great place to interact with developers, and to learn, share, and support each other.
  - type: textarea
    id: description
    attributes:
      label: >
        Description of the bug:
  - type: textarea
    id: behavior
    attributes:
      label: >
        Actual vs expected behavior:
  - type: textarea
    id: info
    attributes:
      label: >
        Any other information you'd like to share?
