# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Semantic AI-Powered Security Auditor for Jupyter Notebooks.

This module acts as the Level 2 (Semantic & Context-Aware) safety gate before running
untrusted or community-submitted pull requests. It uses Gemini to analyze all code
cells in a notebook to detect:
- Backdoor patterns and obfuscated payload execution (e.g. `base64.b64decode` piped into dynamic loaders).
- Data exfiltration attempts (sending API keys or environment variables to unverified external hosts).
- Malicious package dependencies or typo-squatted libraries in `%pip` installs.
- Destructive filesystem or operating system manipulations.

Use Cases:
1. Automated PR auditing before allowing maintainers to run `/test` on community submissions.
2. Generating a structured security verdict (SAFE, SUSPICIOUS, UNSAFE) with risk scoring and explanations.
3. Logging full prompt/response exchanges for complete auditability.
"""

import time
import json
from typing import List, Optional
from pydantic import BaseModel, Field
import nbformat

from google import genai
from google.genai import types

from .config import GLOBAL_CONFIG, TesterConfig
from .logger import logger, log_llm_call


class FlaggedRisk(BaseModel):
    """Represents a specific risk detected in a notebook cell."""
    cell_index: int = Field(description="The 0-based index of the flagged cell.")
    risk_description: str = Field(description="Detailed explanation of the potential threat or malicious pattern.")
    severity: str = Field(description="Severity rating: 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL'.")


class SafetyAuditReport(BaseModel):
    """Structured security audit result generated by Gemini."""
    safety_verdict: str = Field(description="'SAFE' (no threats), 'SUSPICIOUS' (requires human review), or 'UNSAFE' (malicious).")
    risk_score: int = Field(description="Risk rating from 0 (completely safe) to 10 (confirmed malicious).")
    summary: str = Field(description="Concise summary of the security audit findings.")
    external_domains_contacted: List[str] = Field(default_factory=list, description="List of external URLs/domains identified in the code.")
    flagged_risks: List[FlaggedRisk] = Field(default_factory=list, description="List of suspicious or dangerous cells.")


class AISecurityAuditor:
    """Invokes Gemini to perform semantic code security analysis."""

    def __init__(self, config: Optional[TesterConfig] = None):
        """
        Initializes the AI Security Auditor.
        
        Args:
            config: Optional TesterConfig instance.
        """
        self.config = config or GLOBAL_CONFIG
        self.client: Optional[genai.Client] = None
        api_key = self.config.get_api_key()
        if api_key:
            self.client = genai.Client(api_key=api_key)

    def audit_notebook(
        self,
        nb: nbformat.NotebookNode,
        notebook_path: str = ""
    ) -> SafetyAuditReport:
        """
        Performs semantic security review on all code cells of a notebook.
        
        Args:
            nb: Parsed nbformat NotebookNode.
            notebook_path: Path of the notebook for context and logging.
            
        Returns:
            SafetyAuditReport with verdict, risk score, and risk details.
        """
        if self.config.DRY_RUN:
            logger.info(f"[DRY-RUN] Skipping live AI security audit for {notebook_path}")
            return SafetyAuditReport(
                safety_verdict="SAFE",
                risk_score=0,
                summary="[DRY-RUN] Static validation passed; live AI audit skipped.",
                external_domains_contacted=[],
                flagged_risks=[]
            )

        if not self.client:
            logger.warning(
                f"Cannot perform AI security audit for {notebook_path}: "
                f"{self.config.API_KEY_ENV_VAR} is not set."
            )
            return SafetyAuditReport(
                safety_verdict="SUSPICIOUS",
                risk_score=5,
                summary="AI Security Audit skipped due to missing API key.",
                external_domains_contacted=[],
                flagged_risks=[]
            )

        # Build prompt containing all code cells with their index
        code_blocks = []
        for idx, cell in enumerate(nb.cells):
            if cell.cell_type == "code":
                code_blocks.append(f"### Cell {idx}\n```python\n{cell.source or ''}\n```")

        all_code_text = "\n\n".join(code_blocks)

        system_instruction = (
            "You are an expert Cyber Security Code Auditor analyzing Python Jupyter Notebooks "
            "submitted to the Google Gemini API Cookbook open-source repository.\n"
            "Your job is to detect: malicious code, backdoors, environment variable exfiltration "
            "(stealing GEMINI_API_KEY or OS tokens), hidden reverse shells, unauthorized dynamic code "
            "execution (obfuscated eval/exec), dangerous subprocesses, and malicious %pip dependencies.\n"
            "Legitimate code includes: google-genai SDK usage, standard ML/AI libraries, standard matplotlib/pillow/numpy, "
            "and public media downloads from Google Cloud Storage or official Google domains.\n"
            "Evaluate the code strictly and return a structured JSON response matching the SafetyAuditReport schema."
        )

        user_content = (
            f"Notebook Path: {notebook_path}\n\n"
            f"Review the following notebook code cells for security risks:\n\n"
            f"{all_code_text}"
        )

        model_name = self.config.SECURITY_AUDITOR_MODEL
        gen_config = types.GenerateContentConfig(
            system_instruction=system_instruction,
            temperature=0.0,
            response_mime_type="application/json",
            response_schema=SafetyAuditReport
        )

        parameters_dict = {
            "temperature": 0.0,
            "response_mime_type": "application/json",
            "model": model_name
        }

        t0 = time.time()
        try:
            logger.info(f"🛡️ Running Gemini AI Security Audit on {notebook_path} using {model_name}...")
            response = self.client.models.generate_content(
                model=model_name,
                contents=user_content,
                config=gen_config
            )
            duration = time.time() - t0

            raw_text = response.text or "{}"
            log_llm_call(
                feature="AISecurityAuditor",
                model=model_name,
                prompt=user_content,
                parameters=parameters_dict,
                response=raw_text,
                duration_sec=duration,
                metadata={"notebook": notebook_path}
            )

            report_data = json.loads(raw_text)
            report = SafetyAuditReport(**report_data)
            logger.info(
                f"🛡️ Security Audit Result for {notebook_path}: "
                f"Verdict={report.safety_verdict}, RiskScore={report.risk_score}/10"
            )
            return report

        except Exception as e:
            duration = time.time() - t0
            logger.error(f"Error during AI security audit for {notebook_path}: {e}")
            log_llm_call(
                feature="AISecurityAuditor",
                model=model_name,
                prompt=user_content,
                parameters=parameters_dict,
                response=f"ERROR: {e}",
                duration_sec=duration,
                metadata={"notebook": notebook_path, "error": str(e)}
            )
            return SafetyAuditReport(
                safety_verdict="SUSPICIOUS",
                risk_score=6,
                summary=f"Security audit encountered an evaluation error: {e}",
                external_domains_contacted=[],
                flagged_risks=[]
            )
