name: All new notebooks are linked in a README

on:
  pull_request:
    branches: [ main ]
    paths:
      - "**.ipynb"

permissions:
  contents: read

jobs:
  check-readme-links:
    name: Check Table of Contents links
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262  # v4
        with:
          persist-credentials: false
      - uses: actions/setup-python@7f4fc3e22c37d6ff65e88745f38bd3157c663f7c  # v4
      - name: Get Changed Files
        id: changed-files
        uses: tj-actions/changed-files@2f7c5bfce28377bc069a65ba478de0a74aa0ca32  # v46.0.1
        with:
          files:  |
            **.ipynb
          files_ignore: |
            tools/**
            .github/**
      - name: Check README links
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          python3 tools/check_readme_links.py ${{ steps.changed-files.outputs.all_changed_files }}
